//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaWynajmujacies
    {
        public int SalaId { get; set; }
        public int WynajmujacyId { get; set; }
        public System.DateTime DataPoczatkowa { get; set; }
        public System.TimeSpan GodzinaPoczatkowa { get; set; }
        public System.TimeSpan GodzinaKoncowa { get; set; }
        public int SalaWynajmujacyId { get; set; }
    
        public virtual Salas Salas { get; set; }
        public virtual Wynajmujacies Wynajmujacies { get; set; }
    }
}
